visit_list = ["Japan","Sweden","Philippines","Russia","Canada"]
print(visit_list , " Base")
#Alphabetical sort (sorted)
print(sorted(visit_list) , " Alphabetical Sort")
print(visit_list)
#Reverse alphabetical sort (sorted)
print(sorted(visit_list, reverse = True) , " Reverse Alphabetical Sort")
print(visit_list)
#Reversed List
visit_list.reverse()
print(visit_list , " Reverse")
visit_list.reverse()
print(visit_list , " Un-reverse")
#Alphabetical sort (sort)
visit_list.sort()
print(visit_list , " Alphabetical sort 2")
#Reverse alphabetical sort (sort)
visit_list.sort(reverse = True)
print(visit_list , " Reverse Alphabetical sort 2")
